### ISSUE TITLE
-DELETE Does not Delete Container

### ISSUE THREAD

**Issue by afrazkhan** [elastic/elasticsearch-cloud-azure#102]
Sending a DELETE returns:

```
{"acknowledged":true}
```

and Elasticsearch removes the repository, but in Azure it still exists.

**Comment by imotov** [comment]
@afrazkhan When a repository is deleted, Elasticsearch only removes the reference to the location where the repository is storing the snapshots. The snapshots themselves are left untouched and in place.  Please see [snapshot/restore documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) for more information.

**Comment by afrazkhan** [comment]
Yes! Apologies, brain fart on that day. Deleting snapshots works, deleting the repo just deletes the reference. Thanks.
