### ISSUE TITLE
Request for enabling client side encryption in blob

### ISSUE THREAD

**Issue by sachinsan** [elastic/elasticsearch-cloud-azure#103]
First of all thank you for the great plugin. For security reasons, we would like to have encryption enabled on the blob (snapshots) uploaded to azure. Since, Azure blob doesn't support server side encryption it needs client side encryption while uploading and decryption while downloading it. 
I would like to understand if you are going to support the client side encryption in this plugin. It would be a great feature to have in this great plugin. Looking forward to views from contributors. 
Regards,
-Sachin

**Comment by dadoonet** [comment]
I think this could be useful. Not only for azure but for other storages.

I would look at this ticket: https://github.com/elastic/elasticsearch/issues/11128

Closing here as the answer is not in the azure plugin itself but in elasticsearch core.

cc @imotov

**Comment by sachinsan** [comment]
Thank you for your quick reply. But I thought the plugin does the upload to the Azure using java sdk hence thought it is Plugin feature. How can we follow up or anything we could do to promote this feature request.
Thanks once again.

Sachin
Sent from my Samsung device


-------- Original message --------

**Comment by dadoonet** [comment]
You can comment on the other issue and add a `+1` as a comment :)
