### ISSUE TITLE
Github URL leads to a 404

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-cloud-azure#105]
On the main repo page the github url at the top of the page you entered for the azure guide leads to a 404.

**Comment by niemyjski** [comment]
https://www.elastic.co/guide/en/elasticsearch/plugins/master/cloud-azure.html

**Comment by niemyjski** [comment]
Along with the project has moved...

**Comment by dadoonet** [comment]
Thank you. Fixed for now.
