### ISSUE TITLE
Setup cluster for multiple subscriptions

### ISSUE THREAD

**Issue by yellow1912** [elastic/elasticsearch-cloud-azure#106]
I currently have machines in more than 1 subscription connecting via VirtualNetwork. Would the configuration as described in the readme still apply?

**Comment by dadoonet** [comment]
I think it won't work as I believe that azure API will only return the list of machines for one subscription and not for the other one.

May be we could try to support a list of subscription (I mean open multiple azure clients)?

Could you open an issue in elasticsearch repo and refer to this issue as this plugin now lives there?

**Comment by yellow1912** [comment]
Thank you, I added https://github.com/elastic/elasticsearch/issues/14175

**Comment by dadoonet** [comment]
Thanks. Closing this one
