### ISSUE TITLE
Add timeout settings (default to 5 minutes)

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-cloud-azure#109]
Similar to https://github.com/elastic/elasticsearch/issues/15833 , let's also look into the possibility of backport-ing the timeout setting for users on ES 1.7.x since the current workaround involves identifying a production data node that has a hung thread waiting for the Azure client call and restarting that data node to recover.  @dadoonet @clintongormley

**Comment by dadoonet** [comment]
Obviously if we do it, it also needs to be backported in 2.2, 2.1 and 2.0 branches in elasticsearch repo.

**Comment by dadoonet** [comment]
Closed by #111
