### ISSUE TITLE
Support Worker role

### ISSUE THREAD

**Issue by slav** [elastic/elasticsearch-cloud-azure#12]
Is it possible to support Azure worker role and deploy ElasticSearch in it? That would make ElasticSearch deployment fully automated.

**Comment by dadoonet** [comment]
Wondering if the link @garvincasimir shared solves this feature request?
I mean that I don't really know what we could do in the cloud-azure plugin to support such a thing.

Thoughts? Should we close this issue?

**Comment by garvincasimir** [comment]
@dadoonet The great thing about this solution is it does not require you to create certificates or configure virtual machines. Simply point to the installation files for java, Elasticsearch and your desired plugins in your service configuration then configure the service for the number of instances you want and deploy. Another advantage it has is the ability to run locally in the Azure emulator. It can by added to any new or existing WebRole or WorkerRole using the nuget package.

**Comment by dadoonet** [comment]
Closing. Not sure what to do with this thread.
May be a blog post explaining all that would be nice though?
