### ISSUE TITLE
Error when running the template script (deploy.ps1) to create Elasticsearch environment to Azure

### ISSUE THREAD

**Issue by lmemmott** [elastic/elasticsearch-cloud-azure#120]
When running the automation scripts downloaded from Azure from a created ES environment, it errors with the following message:

` 
New-AzureRmResourceGroupDeployment : 5:02:30 PM - Error: Code=InvalidDeploymentParameterValue; Message=The value of deployment parameter 'loadBalancers_es_internal_lb_id_4' is
null. Please specify the value or use the parameter reference. See https://aka.ms/arm-deploy/#parameter-file for details.
At C:\Users\leste\Downloads\ExportedTemplate-ElasticsearchRG2\deploy.ps1:104 char:5
+     New-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGr ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
`

**Comment by dadoonet** [comment]
I'm not sure how this is related to the cloud-azure plugin. In any case this repository is not maintained anymore as per README.

Please ask your question on discuss.elastic.co.

**Comment by lmemmott** [comment]
Thanks for the response.  I was under the assumption that this was the project that developed the "Elastic Stack - (Elasticsearch, Kibana, X-Pack) item in the Azure Marketplace.  I'll keep looking.

**Comment by dadoonet** [comment]
@elastic/microsoft might know

**Comment by Mpdreamz** [comment]
That template is developed by us @lmemmott, it looks like you exported your previous deployment from the portal? We dont support that mode of redeployment. 

If you want to redeploy, redeploy from the command line using the same parameters. See http://github.com/elastic/azure-marketplace for more information.

If you have further questions on let us know through discuss.elastic.co 👍

**Comment by lmemmott** [comment]
@Mpdreamz Thanks for finding my question.  Not sure how you find this thread, but thanks!  I was just going to the URL you mentioned and starting to read through it.  I'll jump to the discussion groups when I have more questions.  Thanks!

**Comment by dadoonet** [comment]
> Not sure how you find this thread, but thanks!

Well... Pinging `@elastic/microsoft` helped here :)
