### ISSUE TITLE
Azure snapshot request returns 500 error: "null_pointer_exception"

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-cloud-azure#123]
I entered an issue on the NEST project but based on the log info, it looks like it must be an azure repository plugin bug but I'm not sure: [Azure snapshot request returns 500 error: "null_pointer_exception"](https://github.com/elastic/elasticsearch-net/issues/3051)

**Comment by dadoonet** [comment]
As per readme this repository is not used anymore.

**Comment by russcam** [comment]
@tdoman Would you mind opening the issue on https://github.com/elastic/elasticsearch/, where the repository now lives?
