### ISSUE TITLE
Accessing Elasticsearch when there are x instances

### ISSUE THREAD

**Issue by flavianh** [elastic/elasticsearch-cloud-azure#36]
What is the best way to query an Elasticsearch cluster ? I've tried load-balancing the connections but it was randomly connecting me to a different node, which was making monitoring through kopf difficult.
So I figured I'd open the 9200 port on only one VM instance but this does not maximize the throughput (since the bandwidth is limited to the bandwidth of a single VM instance). 
What's the best way? Plus, it would be a cool think to add to the doc.

**Comment by traxair** [comment]
In case anyone is interested, I have had a look at elasticsearch-py and they _do_ have implemented this behavior. So if you call `client = Elasticsearch(hosts=<list of hosts>)` then the hosts are put into a __ConnectionPool__ that uses a __ConnectionSelector__, which by default is round robin (__RoundRobinSelector__).

**Comment by dadoonet** [comment]
Going to close it. Not sure if anyone wants to contribute a doc change in elasticsearch repo.
