### ISSUE TITLE
Support new host_type=rdma option

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-cloud-azure#41]
Would like to see support for a `host_type` similar to what we have for the AWS plugin.  For azure, it can be one of the following types:

private_ip
public_ip
RDMA (http://blogs.technet.com/b/windowshpc/archive/2014/01/30/new-high-performance-capabilities-for-windows-azure.aspx)

It will also be nice for it to default to use the better performing RDMA connection and fall back to private_if if none is provided.

**Comment by dadoonet** [comment]
Waiting for #63 to be merged first so we can use Azure API for this.

**Comment by dadoonet** [comment]
I did some tests today and I launched a `A8` Windows instance.
It sounds like that by default Windows machine has 2 network cards `Microsoft Hyper-V Network Adapter`. 
In the documentation, they wrote that:

> We have virtualized RDMA through Hyper-V with near bare metal performance of less than 3 microsecond latency and greater than 3.5 gigabytes per second bandwidth.

So I wonder if we really have to do any change in the plugin code as by default we are using the `private_ip` which correspond to `Microsoft Hyper-V Network Adapter`. Is my understanding correct?

Is there any other setting I missed or any configuration you have to do on the windows machine to explicitly set a `RDMA` card?

**Comment by johnarnold** [comment]
RDMA connectivity is not supported on Linux VMs, FYI.

On Windows machines, you can only leverage it via Network Direct & MPI.  In other words, I don't think you can use it today unless you move off of the regular network stack for inter-node I/O.

I'd love to see faster shard recoveries and such.  With the Premium Storage, we're seeing pretty good write performance, but it still pretty much sucks when you have to reboot stuff or a node dies.

**Comment by dadoonet** [comment]
Closing as now opened at https://github.com/elastic/elasticsearch/issues/12449
