### ISSUE TITLE
Optimize AzureBlobStore#delete method

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-cloud-azure#66]
When we have to remove a lot of files, method `AzureBlobStore#delete` is called for each file and generates a Azure API call.

Would be nice to see if we can batch somehow those calls instead.

**Comment by dadoonet** [comment]
@imotov As far as I understand the core code, I don't really think that it's doable. We need to process file deletion one by one, right?

**Comment by imotov** [comment]
@dadoonet actually when we delete a lot of files, we have a list of blobs that should be deleted and we simply iterate through the list. We can easily modify the logic to pass entire list to the store.

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#12697
