### ISSUE TITLE
CreationException when elasticsearch.yml is incorrect

### ISSUE THREAD

**Issue by LeviBotelho** [elastic/elasticsearch-cloud-azure#86]
I am trying to get Elasticsearch working on an Azure VM with the Azure Elasticsearch plugin. I have followed the steps on the project page right up to the point where I start the service. When I try to start the service I get the following error:

> ...
> [2015-05-16 18:57:36,836][ERROR][bootstrap ] Exception org.elasticsearch.common.inject.CreationException: Guice creation errors:

> 1) No implementation for org.elasticsearch.discovery.Discovery was bound. while locating org.elasticsearch.discovery.Discovery for parameter 2 at org.elasticsearch.discovery.DiscoveryService.(Unknown Source)
at unknown

> 2) No implementation for org.elasticsearch.discovery.Discovery was bound. while locating org.elasticsearch.discovery.Discovery for parameter 3 at org.elasticsearch.node.service.NodeService.(Unknown Source) at unknown

I'm not sure if this is a bug or an error on my part, but if it's human error it would be nice at the very least to have a more descriptive message.

**Comment by dadoonet** [comment]
Which versions?

**Comment by LeviBotelho** [comment]
Elasticsearch: 1.5.2

Elasticsearch Azure Plugin: 2.6.0

Java:

> java version "1.7.0_80"
> Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
> Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by dadoonet** [comment]
Could you share your elasticsearch.yml?
Just replace azure credentials with XXXXX.

**Comment by LeviBotelho** [comment]
Ugh I had an error in my config. Sorry for wasting your time. Thanks for the tip! Works perfectly now.

**Comment by dadoonet** [comment]
Could you tell what the config was looking like?
So we van see if we can detect it better?

**Comment by LeviBotelho** [comment]
My keystore `path` and `password` entries weren't indented, so I'm assuming that they were coming up as `null` when the extension launched, causing the crash.

**Comment by dadoonet** [comment]
Thank you. I reopen your issue and will close it later.
Thanks for the feedback.

**Comment by LeviBotelho** [comment]
Thanks very much. The plugin is excellent. Really appreciate the work you have all done.

**Comment by dadoonet** [comment]
Closing this one as we now have a pending PR at https://github.com/elastic/elasticsearch/issues/15219
