### ISSUE TITLE
AzureMinimumMasterNodesTest is flaky

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch-cloud-azure#89]
This test is usually pretty fast, but sometimes takes forever and fails like this:

HEARTBEAT J0 PID(21202@beast): 2015-05-27T20:16:34, stalled for 11.4s at: AzureMinimumMasterNodesTest.simpleOnlyMasterNodeElection
HEARTBEAT J0 PID(21202@beast): 2015-05-27T20:16:44, stalled for 21.4s at: AzureMinimumMasterNodesTest.simpleOnlyMasterNodeElection
Suite: org.elasticsearch.discovery.azure.AzureMinimumMasterNodesTest
  2> REPRODUCE WITH: mvn test -Pdev -Dtests.seed=C013ECB183D25631 -Dtests.class=org.elasticsearch.discovery.azure.AzureMinimumMasterNodesTest -Dtests.method="simpleOnlyMasterNodeElection" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=ja -Dtests.timezone=SystemV/YST9
  2> REPRODUCE WITH: mvn test -Pdev -Dtests.seed=C013ECB183D25631 -Dtests.class=org.elasticsearch.discovery.azure.AzureMinimumMasterNodesTest -Dtests.method="simpleOnlyMasterNodeElection" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=ja -Dtests.timezone=SystemV/YST9
ERROR   30.5s | AzureMinimumMasterNodesTest.simpleOnlyMasterNodeElection <<<

> Throwable #1: java.lang.AssertionError: 
> Expected: null
>      but: was "cwzALviTRc-mWfuKqztWog"
>    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
>    at org.elasticsearch.discovery.azure.AzureMinimumMasterNodesTest.simpleOnlyMasterNodeElection(AzureMinimumMasterNodesTest.java:77)
>    at java.lang.Thread.run(Thread.java:745)Throwable #2: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
>    at org.elasticsearch.cluster.block.ClusterBlocks.indexBlockedException(ClusterBlocks.java:174)
>    at org.elasticsearch.action.admin.indices.template.delete.TransportDeleteIndexTemplateAction.checkBlock(TransportDeleteIndexTemplateAction.java:61)
>    at org.elasticsearch.action.admin.indices.template.delete.TransportDeleteIndexTemplateAction.checkBlock(TransportDeleteIndexTemplateAction.java:37)
>    at org.elasticsearch.action.support.master.TransportMasterNodeAction.innerExecute(TransportMasterNodeAction.java:92)
>    at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:84)
>    at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:47)
>    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:63)
>    at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
>    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:335)
>    at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1150)
>    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
>    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
>    at org.elasticsearch.test.TestCluster.wipeTemplates(TestCluster.java:175)
>    at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:75)
>    at org.elasticsearch.test.ElasticsearchIntegrationTest.afterInternal(ElasticsearchIntegrationTest.java:670)
>    at org.elasticsearch.test.ElasticsearchIntegrationTest.after(ElasticsearchIntegrationTest.java:1970)
>    at java.lang.Thread.run(Thread.java:745)
>   2> NOTE: leaving temporary files on disk at: /home/rmuir/workspace/elasticsearch/plugins/cloud-azure/target/J0/temp/org.elasticsearch.discovery.azure.AzureMinimumMasterNodesTest C013ECB183D25631-001
>   2> NOTE: test params are: codec=Asserting(Lucene50), sim=DefaultSimilarity, locale=ja, timezone=SystemV/YST9
>   2> NOTE: Linux 3.13.0-49-generic amd64/Oracle Corporation 1.8.0_45 (64-bit)/cpus=8,threads=1,free=377846904,total=513277952
>   2> NOTE: All tests run in this JVM: [AzureSimpleTest, AzureSnapshotRestoreITest, SmbMMapFsTest, AzureMinimumMasterNodesTest]

**Comment by dadoonet** [comment]
Going to close it. So many things changed in master in the mean time and we definitely to invest more time in our cloud test integration infra.

**Comment by DaveCTurner** [comment]
There's a test with this issue listed as `@AwaitsFix` here: https://github.com/elastic/elasticsearch/blob/8d6bfe53bb118f6da74581f10e1100c7f18315f4/plugins/discovery-azure-classic/src/test/java/org/elasticsearch/discovery/azure/classic/AzureMinimumMasterNodesTests.java#L44

This test hasn't run (in `master` anyway) since May 2015. Can we delete it?

**Comment by dadoonet** [comment]
@DaveCTurner this repo is now closed. Everything moved to elasticsearch repo now.
Could you open it there?

We definitely need to write real IT that works all the time and more unit tests and may be IT with AWS API Mocks.
But I'm totally fine of removing that old code that has not been launched for years may be.
